language: python
python:
  - 3.0
  - 3.5
  - 3.6
services:
  - mongodb
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - nosetests --with-coverage
after_success:
  - coveralls